{"run_number": "1680188525285397", "step_name": "create_tables", "task_id": "2", "attempt_id": 0, "name": "_exception", "content_type": "gzip+pickle-v2", "type": "metaflow.artifact", "sha": "f3627f46179fdd95bf0e83101840fd1d71b60e40", "ds_type": "s3", "location": ":root:s3://metaflow-data", "flow_id": "CreateTablesFlow", "user_name": "jovyan", "tags": [], "system_tags": ["user:jovyan", "runtime:dev", "python_version:3.10.9", "metaflow_version:2.7.23"], "ts_epoch": 1680188537648}